# fly.toml app configuration file generated for makcik-fatimah on 2026-05-15T15:05:14+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'makcik-fatimah'
primary_region = 'sin'

[build]

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
